"""add professional service association

Revision ID: 32e97b38046d
Revises: 6604689ef554
Create Date: 2026-10-09 18:16:55.109302

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "32e97b38046d"
down_revision = "6604689ef554"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "professionals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("establishment_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["establishment_id"],
            ["establishments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "professional_services",
        sa.Column("professional_id", sa.Integer(), nullable=False),
        sa.Column("service_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["professional_id"],
            ["professionals.id"],
        ),
        sa.ForeignKeyConstraint(
            ["service_id"],
            ["services.id"],
        ),
        sa.PrimaryKeyConstraint("professional_id", "service_id"),
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table("professional_services")
    op.drop_table("professionals")
    # ### end Alembic commands ###
